import Head from 'next/head';
import { useState } from 'react';
import Guest from '../components/Guest';
import User from '../components/User';
import {getSession,useSession,signOut} from "next-auth/react"

export default function Home() {
  const {data : session} = useSession()
  async function handleSignout (){
    signOut()
  }
  return (
    <div className=''>
      <Head>
        <title>Fullstack Next Js Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen bg-gray-400 flex justify-center'>
        {session ? <User session={session} handleSignout={handleSignout}/> : <Guest/>}
      </div>
    </div>
  )
}

export async function getServerSideProps({req}) {
  const session = await getSession({req})
  if(!session){
    return {
      redirect : {
        destination : '/user/signin',
        parmanent : false
      }
    }
  }
  return{
    props : {session}
  }
}